# Generated by Django 5.0 on 2024-01-16 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_tutionmodel_hotelmodel'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBankAccountModel',
            new_name='UserAccountModel',
        ),
    ]
