# Generated by Django 5.0 on 2024-01-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutionModel',
            new_name='HotelModel',
        ),
    ]
