# Generated by Django 5.0 on 2024-01-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_tutionmodel_hotelmodel'),
        ('users', '0002_rename_userbankaccountmodel_useraccountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('booking_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccountmodel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelmodel')),
            ],
        ),
    ]
